from .user import *
from .admin import *
from .staff import *
from .course import *
from .programme import *
from .assessment import *
from .courseStaff import *
from .courseAssessment import *
from .programmeCourse import *
from .semester import *
