from .user import *
from .admin import *
from .staff import *
from .course import *
from .programme import *
from .assessment import *
from .courseStaff import *
from .programmeCourse import *
from .semester import *
from .courseOffering import *
from .categoryGroup import *
from .category import *
